### ISSUE TITLE
Compiling for iOS

### ISSUE THREAD

**Issue by notlion** [Reactive-Extensions/RxCpp#19]
Clang gives this error when compiling for iOS (arm64):

```
In file included from ../deps/rxcpp/Rx/v2/src/rxcpp/rx.hpp:8:
In file included from ../deps/rxcpp/Rx/v2/src/rxcpp/rx-includes.hpp:124:
In file included from ../deps/rxcpp/Rx/v2/src/rxcpp/rx-scheduler.hpp:861:
../deps/rxcpp/Rx/v2/src/rxcpp/schedulers/rx-currentthread.hpp:35:16: error: thread-local storage is unsupported for the current target
        static RXCPP_THREAD_LOCAL current_thread_queue_type* queue;
```

Version info (Xcode 5.1.1):
```
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.2.0
Thread model: posix
```

I get this for both device and simulator builds. Apologies if Rx isn't supported on iOS yet. I'm curious to check it out!

**Comment by ildarsharafutdinov** [comment]
@notlion, have you managed to test your solution for iOS?

I'm not 100% sure, but:

```
static RXCPP_THREAD_LOCAL current_thread_queue_type* queue;
```

As far as I understand there should be 1 instance of **queue** for each thread.

```
static thread_local_storage<current_thread_queue_type> queue;
```

However, in your solution there is a single copy of **queue** which is shared among all threads. And using **pthread_*** calls doesn't change the situation, because **thread_local_storage** constructor is called once and creates a single **key_**.

**Comment by notlion** [comment]
@ildarsharafutdinov Not outside of compilation. In the end I decided to go with a signals/slots implementation since my use case didn't require most of what RxCpp is capable of.

**Comment by kirkshoop** [comment]
@ValeryKopylov has applied this fix. 25dbb1162d5379fc86e85d9a3fae3e101ab67e8c
