### ISSUE TITLE
Default coordination on iterate

### ISSUE THREAD

**Issue by i94matjo** [Reactive-Extensions/RxCpp#194]
Is there a reason why 'iterate' operator has 'identity_current_thread' as a default coordination, while for example 'from' uses 'identity_immediate' as default? I happend to miss this and assumed immediate and got results I did not expect.
Thanks for a great library!
/Mattias

**Comment by kirkshoop** [comment]
Thanks for asking!

rxcpp follows the .Net pattern for sources like range and iterate. the default is current_thread so that a merge of multiple sources will interleave rather than concatenate.

concat can be easily applied to streams on current_thread, while interleaving sources on immediate is not easy. without back-pressure, trying to interleave immediate sources introduces queues that soak up the entire source - this plays havoc with memory pressure and cancellation (in partucular the take operator).
