### ISSUE TITLE
RAII subscription

### ISSUE THREAD

**Issue by martinfinke** [Reactive-Extensions/RxCpp#215]
Does the `rxcpp::subscription` always call `unsubscribe` on itself when it's destroyed? I looked at the source code but couldn't see it for sure because there was inheritance, etc.
I figure it doesn't, because otherwise when you call `observable::subscribe` and don't use the return value, the subscription would immediately be removed again.

If not, how about a RAII subscription class (template) that automatically does that? When connecting rxcpp stuff to other frameworks, I often use subscriptions as class members to react to an observable and call framework code. It would be good to not have to write `subscription.unsubscribe()` in a lot of destructors.

**Comment by kirkshoop** [comment]
Thanks for the question! 

No, subscription does not call unsubscribe from its destructor. As you say, rxcpp would not work at all if it did.

The lifetime of an async operation always contains RAII scoped objects, but I struggle to see cases where the async operation lifetime should be scoped by RAII. The common case for RAII over an async operation is implemented in rxcpp by as_blocking().subscribe() which blocks the calling thread until completion.

since unsubscribe represents cancellation (and it is async cancellation, unsubscribe returns before the operation has finished the teardown) it is not a good match for scope exit or deallocation. I would be careful about calling unsubscribe from destructors.

keep in mind that async lifetime often introduces circular references between participants in the operation since the lifetime of their allocation must exceed the lifetime of the operation, but there is no block in the code that represents the async lifetime. the unsubscribe function is the way that these circular references are broken and placing RAII members in participating classes might result in unsubscribe never being called at all due to the circular references preventing any destructors from running.

now that the exhaustive list of concerns is finished, I can talk about adding a subscription_guard RAII type. This could be added to rxcpp despite my concerns because if it exists we can learn how useful or harmful it is in real code. It does not need to be a template since subscription is a concrete type. it should be a very simple class to write. I would merge a PR for subscription_guard.

**Comment by martinfinke** [comment]
Thanks for the reply!

I think we're talking about different use cases. I think you're referring to async operations like network requests. But I'm using rxcpp for model-view binding.
Let's say I have a game, and I represent the x/y coordinates of the player as a `rxcpp::subjects::behavior<Point> position`. After it's initialized, this `behavior` lives until the program quits.

I then have a `PlayerView` which is a view in a framework. It also lives until the program quits. It has a member `subscription` that is initialized with `position.get_observable().subscribe(someFunction)`. `someFunction` updates the view position. In `~PlayerView()`, I call `subscription.unsubscribe()`.

This somehow causes leaks. What's the correct way to do this?

**Comment by kirkshoop** [comment]
Thanks for the additional details.

Calling `unsubscribe()` on the result of `subscribe()` only stops the `PlayerView` subscription to the `position`. It does not stop the `position`. 

Subjects have two ends. The `observable` end has a subscription per subscribe, however, the `subscriber` end has a subscription as well. When shutting down, the `subscriber` should have `completed()` or `unsubscribe()` called. This will stop all the subscriptions as well.

This means that `PlayerView` does not need to store the subscription or call unsubscribe. The only time to store and call a subscription returned from `subscribe()` is to control its lifetime independently from its source (even then, use `take_until()` whenever possible). Since `PlayerView` "lives until the program quits" the shutdown should be used to stop the position `subscriber` instead.

**Comment by martinfinke** [comment]
Thank you for your time and help. I really appreciate the help I'm getting here, because I'm sometimes struggling with the Doxygen docs.
I was searching for the source of the leaks for hours. The reason was that I was not calling `on_completed` on the `subscriber` of the Subject.

I have written some very simple wrappers that do the RAII behavior I need. I'm closing the issue because  I'm not sure it should be part of rxcpp. Of course you're welcome to re-open if you want to add it.

**Comment by kirkshoop** [comment]
I am happy to help!

If you would like to take another step towards adding raii, I would suggest pushing a branch on a fork of rxcpp that has a new example showing the intended use cases for the raii types.  

Thanks!

**Comment by jzrake** [comment]
I have a similar use case as martinfinke, also in a model-view setting.

A view update method is subscribed to an observable (via lambda capturing `this`). A memory error would ensue if the subscription were to outlive the view instance. Therefore, I need the subscription to end deterministically on the view's destructor. This sounds like a case for RAII.

Kirkshoop, please comment - is this a misuse of rx?

Thank you very much,
Zrake

**Comment by martinfinke** [comment]
This is not directly an answer to your question (Kirk is the authority there), but I just want to share some ideas I found around this issue.

Other Rx implementations have a `DisposeBag`, which I believe is similar to `rxcpp`'s `composite_subscription`, except that it also unsubscribes all added subscriptions automatically when destroyed.

In use, it looks a little like this:
```
disposeBag.add(someObservable.subscribe([this](…){…}));
```

and your class has a member `DisposeBag disposeBag;`, preferably the last data member of the class.

Nowadays I prefer a pattern I've borrowed from RxSwift:

```
someObservable.take_until(destroyed).subscribe([this](…){…});
```
The advantage is that you don't have something extra parentheses around the whole thing. The `destroyed` variable is just a custom Observable that emits once when it's destroyed. You can implement this class easily using `rxcpp::subjects::replay`.

**Comment by jzrake** [comment]
Thanks for the reply.

Since writing that post, I thought of that same solution using `take_until` and a `Sentinal` class that emits on its destruction. You just put a `Sentinal` in your data members (LAST, so that it emits before your other data members are destroyed). Then there's no need to keep subscriptions, or to add a destructor solely to call `unsubscribe`.

BTW - I also discovered (adapted from Kirk's blog [here](http://kirkshoop.github.io/async/rxcpp/c++/2015/08/04/rxcpp_-_moderncpp_events_as_observables.html)) how to eliminate subjects altogether using a `from_event` factory, which AFAIK is not part of `rxcpp`. This means there's no need for your class to have any `rxcpp` data members, which I suspect might be a good thing.

**Comment by martinfinke** [comment]
> LAST, so that it emits before your other data members are destroyed

Yes, very important. I forgot to write that in my post. My class is called `DestroyNotifier`, and it's `final`, to prevent from inheriting from it (it won't do what you want).
