### ISSUE TITLE
subject.has_observers() always returns TRUE

### ISSUE THREAD

**Issue by fbunn** [Reactive-Extensions/RxCpp#348]
When I create a subject and call the 'has_observers()', it return true;

Is there a way to know how many subscribers there are for a subject?

And what's the difference between 'unsubscribe()' and 'remove()'?

Thanks!

**Comment by kirkshoop** [comment]
Hi!

I verified that `has_observers()` only returns true when there is at least one active subscription.

There is no way to ask the subject for the number of active subscriptions. If there were then using it would be discouraged, just like `has_observers()` every result from these functions is a race because `subscribe()` supports calls from multiple threads. To process subscription and unsubscription to a subject, add an operator to hook `subscribe()` and `unsubscribe()` to the result of `get_observable()` and call `subscribe()` on that instead.

- `unsubscribe()` will cancel an active subscription. This disconnects the `subscriber` from the `observable`.
- `remove()` will disconnect a dependency between two subscriptions. `remove()` is available on `composite_subscription` which represents a graph of dependent asynchronous lifetimes.

**Comment by kirkshoop** [comment]
please reopen if you have more questions
